name = "The Table Packwiz"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63267ea5e31b270c19020c345744bdd3deb34e85b257e8b70e7cec41adf2d131"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
