name = "The Table Packwiz"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cca557d28f39d3fcb1bcbc94f9b83a8842867421a4a6055d5e4b6cbb27e3e3ef"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
