name = "The Table Packwiz"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db8742b90bb439d182d585d980bc5e9695b23d87626604a34c20fae7221bb06e"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
