name = "The Table Packwiz"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd32800041231949523237856656aa655e2b241a868ae7c8477100ec8f88faf1"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
