name = "The Table Packwiz"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1bf0f891363c825de3f9dd9e5c31a4827095196f5a5a7c8a87dc87decb43aae"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
