name = "The Table Packwiz"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "651527ca4f32b7d9baf29fe032fae4f08d7f8aacec0ce752b4e9cb388642e4cc"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
