name = "The Table Packwiz"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cd2ff44b9ae790edae4e480f6fb5e9e7b5ff8c85a23852cefe1d2e92fc756a8"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
