name = "The Table Packwiz"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ec9a3e5cc5fc94db9401672f2b9094d96fb9c76d66b0cb7a40854acae0d0fd4"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
