name = "The Table Packwiz"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c8d3fb78cda0a5ee80c3605ddd15aba1a9e4835a892e738daf4ebfe5351e980"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
