name = "The Table Packwiz"
author = "Jonathan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10b77712851ab74c5a8f297cb71dfe260bc781fe91ea675591958b7d12b5f3ca"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
